// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApLUXYR1bzkJIIoj97LGpfPmpisu_B-NA',
    appId: '1:1056960939490:web:b2c357cef9ec60c84a65bb',
    messagingSenderId: '1056960939490',
    projectId: 'localibusao',
    authDomain: 'localibusao.firebaseapp.com',
    storageBucket: 'localibusao.firebasestorage.app',
    measurementId: 'G-80K279YKVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChZeqP9pycHTkarekflpVrVPb1N0k4Mn4',
    appId: '1:1056960939490:android:ab871b4d4127f22b4a65bb',
    messagingSenderId: '1056960939490',
    projectId: 'localibusao',
    storageBucket: 'localibusao.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoKPAGwK5vPwUHbOzJOE0GxzIyAyddXA0',
    appId: '1:1056960939490:ios:044982c6070abe1e4a65bb',
    messagingSenderId: '1056960939490',
    projectId: 'localibusao',
    storageBucket: 'localibusao.firebasestorage.app',
    iosBundleId: 'br.com.localibusao',
  );
}
